= Lab 1 - From Zero to Pushing Your First Application

== Target & Env Setup

. If you haven't already, you should have the latest release of the Cloud Foundry CLI from https://github.com/cloudfoundry/cli/releases for your operating system installed.

. Set the API target for the CLI: (set appropriate end point for your environment)
+
----
$ cf api https://api.run.pez.pivotal.io --skip-ssl-validation
----
. Stage the appropriate files (spring-music.war, manifest.yml) in a directory you can access.  It's important the files are placed in the same directory.
+

----
$ cf login
----
+
Follow the prompts

== Push It!

. Change to the directory where you placed_spring_music.war and manifest.yml:
+
----
$ cd /sample_apps_directory
----

. Push the application!
+
----
$ cf push
----
+
You should see output similar to the following listing. Take a look at the listing callouts for a play-by-play of what's happening:
+
====
----
Using manifest file /Users/weplea/Documents/boeingWorkshop/manifest.yml

Creating app spring-music-copy in org pivot-awepler / space development as awepler@pivotal.io...
OK

Creating route spring-music-copy-unmomentous-trader.cfapps.pez.pivotal.io...
OK

Binding spring-music-copy-unmomentous-trader.cfapps.pez.pivotal.io to spring-music-copy...
OK

Uploading spring-music-copy...
Uploading app files from: /Users/weplea/Documents/boeingWorkshop/spring-music.war
Uploading 457K, 88 files
Done uploading               
OK

Starting app spring-music-copy in org pivot-awepler / space development as awepler@pivotal.io...
Downloading java_buildpack_offline...
Downloading ruby_buildpack...
Downloading nodejs_buildpack...
Downloading go_buildpack...
Downloading python_buildpack...
Downloading php_buildpack...
Downloading staticfile_buildpack...
Downloading binary_buildpack...
Downloading null_buildpack...
Downloading tc_server_buildpack_offline...
Downloading secure-java-buildpack...
Downloaded java_buildpack_offline
Downloaded python_buildpack
Downloaded null_buildpack
Downloaded secure-java-buildpack
Downloaded staticfile_buildpack
Downloaded php_buildpack
Downloaded nodejs_buildpack
Downloaded go_buildpack
Downloaded binary_buildpack
Downloaded ruby_buildpack
Downloaded tc_server_buildpack_offline
Creating container
Successfully created container
Downloading app package...
Downloaded app package (24.5M)
Staging...
-----> Java Buildpack Version: v3.6 (offline) | https://github.com/cloudfoundry/java-buildpack.git#5194155
-----> Downloading Open Jdk JRE 1.8.0_71 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_71.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.1s)
-----> Downloading Open JDK Like Memory Calculator 2.0.1_RELEASE from https://download.run.pivotal.io/memory-calculator/trusty/x86_64/memory-calculator-2.0.1_RELEASE.tar.gz (found in cache)
       Memory Settings: -XX:MetaspaceSize=64M -Xss995K -Xmx382293K -XX:MaxMetaspaceSize=64M -Xms382293K
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Instance 8.0.30 from https://download.run.pivotal.io/tomcat/tomcat-8.0.30.tar.gz (found in cache)
       Expanding Tomcat Instance to .java-buildpack/tomcat (0.1s)
-----> Downloading Tomcat Lifecycle Support 2.5.0_RELEASE from https://download.run.pivotal.io/tomcat-lifecycle-support/tomcat-lifecycle-support-2.5.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Logging Support 2.5.0_RELEASE from https://download.run.pivotal.io/tomcat-logging-support/tomcat-logging-support-2.5.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Access Logging Support 2.5.0_RELEASE from https://download.run.pivotal.io/tomcat-access-logging-support/tomcat-access-logging-support-2.5.0_RELEASE.jar (found in cache)
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (108B)
Uploaded droplet (76.7M)
Uploading complete

0 of 2 instances running, 2 starting
0 of 2 instances running, 2 starting
2 of 2 instances running

App started


OK

App spring-music-copy was started using this command `CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.1_RELEASE -memorySizes=metaspace:64m.. -memoryWeights=heap:75,metaspace:10,native:10,stack:5 -memoryInitials=heap:100%,metaspace:100% -totMemory=$MEMORY_LIMIT) &&  JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY -Daccess.logging.enabled=false -Dhttp.port=$PORT" exec $PWD/.java-buildpack/tomcat/bin/catalina.sh run`

Showing health and status for app spring-music-copy in org pivot-awepler / space development as awepler@pivotal.io...
OK

requested state: started
instances: 2/2
usage: 512M x 2 instances
urls: spring-music-copy-unmomentous-trader.cfapps.pez.pivotal.io
last uploaded: Thu Apr 14 17:24:17 UTC 2016

     state     since                    cpu    memory           disk   
#0   running   2016-04-14 10:25:17 AM   0.0%   0 of 512M        0 of 1G   
#1   running   2016-04-14 10:25:19 AM   0.0%   320.8M of 512M   158.4M of 1G 
----
<1> The CLI is using a manifest to provide necessary configuration details such as application name, memory to be allocated, and path to the application artifact.
Take a look at `manifest.yml` to see how.
<2> In most cases, the CLI indicates each Cloud Foundry API call as it happens.
In this case, the CLI has created an application record for _Workshop_ in your assigned space.
<3> All HTTP/HTTPS requests to applications will flow through Cloud Foundry's front-end router called http://docs.cloudfoundry.org/concepts/architecture/router.html[(Go)Router].
Here the CLI is creating a route with random word tokens inserted (again, see `manifest.yml` for a hint!) to prevent route collisions across the default `devcloudwest.inbcu.com` domain.
<4> Now the CLI is _binding_ the created route to the application.
Routes can actually be bound to multiple applications to support techniques such as http://www.mattstine.com/2013/07/10/blue-green-deployments-on-cloudfoundry[blue-green deployments].
<5> The CLI finally uploads the application bits to Pivotal Cloudfoundry. Notice that it's uploading _75 files_! This is because Cloud Foundry actually explodes a ZIP artifact before uploading it for caching purposes.
<6> Now we begin the staging process. The https://github.com/cloudfoundry/java-buildpack[Java Buildpack] is responsible for assembling the runtime components necessary to run the application.
<7> Here we see the version of the JRE that has been chosen and installed.
<8> The complete package of your application and all of its necessary runtime components is called a _droplet_.
Here the droplet is being uploaded to Pivotal Cloudfoundry's internal blobstore so that it can be easily copied to one or more _http://docs.cloudfoundry.org/concepts/architecture/execution-agent.html[Droplet Execution Agents (DEA's)]_ for execution.
<9> The CLI tells you exactly what command and argument set was used to start your application.
<10> Finally the CLI reports the current status of your application's health.
====

. Visit the application in your browser by hitting the route that was generated by the CLI or availabe in the apps manager:
+
requested state: started
instances: 2/2
usage: 512M x 2 instances
urls: spring-music-copy-unmomentous-trader.cfapps.pez.pivotal.io
last uploaded: Thu Apr 14 17:24:17 UTC 2016

== Interact with App from CF CLI

. Get information about the currently deployed application using CLI apps command:
+
----
$ cf apps
----
+
Note the application name for next steps

. Get information about running instances, memory, CPU, and other statistics using CLI instances command
+
----
$ cf app <<app_name>>
----

. Stop the deployed application using the CLI
+
----
$ cf stop <<app_name>>
----

. Delete the deployed application using the CLI
+
----
$ cf delete <<app_name>>
----
